return {
	Porcelain = Color3.fromRGB(238, 236, 229), Graphite = Color3.fromRGB(23, 35, 42),
	Champagne = Color3.fromRGB(206, 183, 132), Limestone = Color3.fromRGB(171, 166, 154),
	Lagoon = Color3.fromRGB(102, 181, 196), Walnut = Color3.fromRGB(97, 71, 57),
	Glass = Color3.fromRGB(49, 80, 92), Green = Color3.fromRGB(122, 194, 159),
	Red = Color3.fromRGB(234, 125, 111), White = Color3.fromRGB(255, 245, 218),
}
